export const STATUS_LABELS: Record<string, string> = {
  draft: "Brouillon",
  received: "Demande reçue",
  under_review: "En cours d'étude",
  option_proposed: "Option proposée",
  option_accepted: "Option acceptée",
  awaiting_client_confirmation: "En attente de votre confirmation",
  confirmed_by_client: "Confirmée par vous",
  confirmed_final: "Confirmée définitivement",
  scheduled: "Formation planifiée",
  completed: "Formation réalisée",
  cancelled_by_client: "Annulée par vous",
  cancelled_by_admin: "Annulée par l'administrateur",
  refused: "Refusée",
  expired: "Expirée",
  archived: "Archivée",
};

export const STATUS_COLORS: Record<string, string> = {
  draft: "bg-neutral-100 text-neutral-500",
  received: "bg-blue-50 text-blue-700",
  under_review: "bg-blue-50 text-blue-700",
  option_proposed: "bg-amber-50 text-amber-700",
  option_accepted: "bg-amber-50 text-amber-700",
  awaiting_client_confirmation: "bg-amber-50 text-amber-700",
  confirmed_by_client: "bg-green-50 text-green-700",
  confirmed_final: "bg-green-50 text-green-700",
  scheduled: "bg-green-50 text-green-700",
  completed: "bg-green-50 text-green-700",
  cancelled_by_client: "bg-red-50 text-red-700",
  cancelled_by_admin: "bg-red-50 text-red-700",
  refused: "bg-red-50 text-red-700",
  expired: "bg-neutral-100 text-neutral-500",
  archived: "bg-neutral-100 text-neutral-500",
};
